// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: plugin/proto/model_provider.proto

package pluginproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelProviderPlugin_GetInfo_FullMethodName        = "/weknora.plugin.v1.ModelProviderPlugin/GetInfo"
	ModelProviderPlugin_ValidateConfig_FullMethodName = "/weknora.plugin.v1.ModelProviderPlugin/ValidateConfig"
	ModelProviderPlugin_Infer_FullMethodName          = "/weknora.plugin.v1.ModelProviderPlugin/Infer"
	ModelProviderPlugin_InferStream_FullMethodName    = "/weknora.plugin.v1.ModelProviderPlugin/InferStream"
)

// ModelProviderPluginClient is the client API for ModelProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelProviderPluginClient interface {
	GetInfo(ctx context.Context, in *ModelProviderInfoRequest, opts ...grpc.CallOption) (*ModelProviderInfoResponse, error)
	ValidateConfig(ctx context.Context, in *ModelProviderValidateRequest, opts ...grpc.CallOption) (*ModelProviderValidateResponse, error)
	// Available only when GetInfo.transport is grpc_inference. JSON schemas are
	// defined in plugin/sdk/model; these are WeKnora operations, not vendor APIs.
	Infer(ctx context.Context, in *ModelInferenceRequest, opts ...grpc.CallOption) (*ModelInferenceResponse, error)
	InferStream(ctx context.Context, in *ModelInferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelInferenceResponse], error)
}

type modelProviderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderPluginClient(cc grpc.ClientConnInterface) ModelProviderPluginClient {
	return &modelProviderPluginClient{cc}
}

func (c *modelProviderPluginClient) GetInfo(ctx context.Context, in *ModelProviderInfoRequest, opts ...grpc.CallOption) (*ModelProviderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelProviderInfoResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) ValidateConfig(ctx context.Context, in *ModelProviderValidateRequest, opts ...grpc.CallOption) (*ModelProviderValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelProviderValidateResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) Infer(ctx context.Context, in *ModelInferenceRequest, opts ...grpc.CallOption) (*ModelInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInferenceResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) InferStream(ctx context.Context, in *ModelInferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelInferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelProviderPlugin_ServiceDesc.Streams[0], ModelProviderPlugin_InferStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModelInferenceRequest, ModelInferenceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProviderPlugin_InferStreamClient = grpc.ServerStreamingClient[ModelInferenceResponse]

// ModelProviderPluginServer is the server API for ModelProviderPlugin service.
// All implementations must embed UnimplementedModelProviderPluginServer
// for forward compatibility.
type ModelProviderPluginServer interface {
	GetInfo(context.Context, *ModelProviderInfoRequest) (*ModelProviderInfoResponse, error)
	ValidateConfig(context.Context, *ModelProviderValidateRequest) (*ModelProviderValidateResponse, error)
	// Available only when GetInfo.transport is grpc_inference. JSON schemas are
	// defined in plugin/sdk/model; these are WeKnora operations, not vendor APIs.
	Infer(context.Context, *ModelInferenceRequest) (*ModelInferenceResponse, error)
	InferStream(*ModelInferenceRequest, grpc.ServerStreamingServer[ModelInferenceResponse]) error
	mustEmbedUnimplementedModelProviderPluginServer()
}

// UnimplementedModelProviderPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderPluginServer struct{}

func (UnimplementedModelProviderPluginServer) GetInfo(context.Context, *ModelProviderInfoRequest) (*ModelProviderInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedModelProviderPluginServer) ValidateConfig(context.Context, *ModelProviderValidateRequest) (*ModelProviderValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedModelProviderPluginServer) Infer(context.Context, *ModelInferenceRequest) (*ModelInferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedModelProviderPluginServer) InferStream(*ModelInferenceRequest, grpc.ServerStreamingServer[ModelInferenceResponse]) error {
	return status.Error(codes.Unimplemented, "method InferStream not implemented")
}
func (UnimplementedModelProviderPluginServer) mustEmbedUnimplementedModelProviderPluginServer() {}
func (UnimplementedModelProviderPluginServer) testEmbeddedByValue()                             {}

// UnsafeModelProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderPluginServer will
// result in compilation errors.
type UnsafeModelProviderPluginServer interface {
	mustEmbedUnimplementedModelProviderPluginServer()
}

func RegisterModelProviderPluginServer(s grpc.ServiceRegistrar, srv ModelProviderPluginServer) {
	// If the following call panics, it indicates UnimplementedModelProviderPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProviderPlugin_ServiceDesc, srv)
}

func _ModelProviderPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelProviderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).GetInfo(ctx, req.(*ModelProviderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelProviderValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).ValidateConfig(ctx, req.(*ModelProviderValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).Infer(ctx, req.(*ModelInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_InferStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModelInferenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelProviderPluginServer).InferStream(m, &grpc.GenericServerStream[ModelInferenceRequest, ModelInferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProviderPlugin_InferStreamServer = grpc.ServerStreamingServer[ModelInferenceResponse]

// ModelProviderPlugin_ServiceDesc is the grpc.ServiceDesc for ModelProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.ModelProviderPlugin",
	HandlerType: (*ModelProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ModelProviderPlugin_GetInfo_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _ModelProviderPlugin_ValidateConfig_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _ModelProviderPlugin_Infer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InferStream",
			Handler:       _ModelProviderPlugin_InferStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/proto/model_provider.proto",
}
