// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: plugin/proto/datasource.proto

package pluginproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{1}
}

type GetInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ConnectorType   string                 `protobuf:"bytes,4,opt,name=connector_type,json=connectorType,proto3" json:"connector_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GetInfoResponse) GetConnectorType() string {
	if x != nil {
		return x.ConnectorType
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{4}
}

func (x *ListResourcesRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ListResourcesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type Resource struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExternalId          string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url                 string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ModifiedAtUnixMilli int64                  `protobuf:"varint,6,opt,name=modified_at_unix_milli,json=modifiedAtUnixMilli,proto3" json:"modified_at_unix_milli,omitempty"`
	ParentId            string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasChildren         bool                   `protobuf:"varint,8,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	MetadataJson        []byte                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetModifiedAtUnixMilli() int64 {
	if x != nil {
		return x.ModifiedAtUnixMilli
	}
	return 0
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *Resource) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{6}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResolveResourceAncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResourceAncestorsRequest) Reset() {
	*x = ResolveResourceAncestorsRequest{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResourceAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResourceAncestorsRequest) ProtoMessage() {}

func (x *ResolveResourceAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResourceAncestorsRequest.ProtoReflect.Descriptor instead.
func (*ResolveResourceAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveResourceAncestorsRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ResolveResourceAncestorsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type Ancestors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ExternalIds   []string               `protobuf:"bytes,2,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ancestors) Reset() {
	*x = Ancestors{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ancestors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ancestors) ProtoMessage() {}

func (x *Ancestors) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ancestors.ProtoReflect.Descriptor instead.
func (*Ancestors) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{8}
}

func (x *Ancestors) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Ancestors) GetExternalIds() []string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

type ResolveResourceAncestorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ancestors     []*Ancestors           `protobuf:"bytes,1,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResourceAncestorsResponse) Reset() {
	*x = ResolveResourceAncestorsResponse{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResourceAncestorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResourceAncestorsResponse) ProtoMessage() {}

func (x *ResolveResourceAncestorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResourceAncestorsResponse.ProtoReflect.Descriptor instead.
func (*ResolveResourceAncestorsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveResourceAncestorsResponse) GetAncestors() []*Ancestors {
	if x != nil {
		return x.Ancestors
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	CursorJson    []byte                 `protobuf:"bytes,3,opt,name=cursor_json,json=cursorJson,proto3" json:"cursor_json,omitempty"`
	Full          bool                   `protobuf:"varint,4,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{10}
}

func (x *FetchRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *FetchRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *FetchRequest) GetCursorJson() []byte {
	if x != nil {
		return x.CursorJson
	}
	return nil
}

func (x *FetchRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type FetchedItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExternalId         string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content            []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType        string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileName           string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Url                string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	UpdatedAtUnixMilli int64                  `protobuf:"varint,7,opt,name=updated_at_unix_milli,json=updatedAtUnixMilli,proto3" json:"updated_at_unix_milli,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDeleted          bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	SourceResourceId   string                 `protobuf:"bytes,10,opt,name=source_resource_id,json=sourceResourceId,proto3" json:"source_resource_id,omitempty"`
	ReplacesSubtree    bool                   `protobuf:"varint,11,opt,name=replaces_subtree,json=replacesSubtree,proto3" json:"replaces_subtree,omitempty"`
	SubtreeKeep        []string               `protobuf:"bytes,12,rep,name=subtree_keep,json=subtreeKeep,proto3" json:"subtree_keep,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FetchedItem) Reset() {
	*x = FetchedItem{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchedItem) ProtoMessage() {}

func (x *FetchedItem) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchedItem.ProtoReflect.Descriptor instead.
func (*FetchedItem) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{11}
}

func (x *FetchedItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FetchedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchedItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchedItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FetchedItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FetchedItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchedItem) GetUpdatedAtUnixMilli() int64 {
	if x != nil {
		return x.UpdatedAtUnixMilli
	}
	return 0
}

func (x *FetchedItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FetchedItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *FetchedItem) GetSourceResourceId() string {
	if x != nil {
		return x.SourceResourceId
	}
	return ""
}

func (x *FetchedItem) GetReplacesSubtree() bool {
	if x != nil {
		return x.ReplacesSubtree
	}
	return false
}

func (x *FetchedItem) GetSubtreeKeep() []string {
	if x != nil {
		return x.SubtreeKeep
	}
	return nil
}

type FetchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FetchEvent_Item
	//	*FetchEvent_CheckpointCursorJson
	//	*FetchEvent_FinalCursorJson
	Payload       isFetchEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEvent) Reset() {
	*x = FetchEvent{}
	mi := &file_plugin_proto_datasource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEvent) ProtoMessage() {}

func (x *FetchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_datasource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEvent.ProtoReflect.Descriptor instead.
func (*FetchEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_datasource_proto_rawDescGZIP(), []int{12}
}

func (x *FetchEvent) GetPayload() isFetchEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchEvent) GetItem() *FetchedItem {
	if x != nil {
		if x, ok := x.Payload.(*FetchEvent_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *FetchEvent) GetCheckpointCursorJson() []byte {
	if x != nil {
		if x, ok := x.Payload.(*FetchEvent_CheckpointCursorJson); ok {
			return x.CheckpointCursorJson
		}
	}
	return nil
}

func (x *FetchEvent) GetFinalCursorJson() []byte {
	if x != nil {
		if x, ok := x.Payload.(*FetchEvent_FinalCursorJson); ok {
			return x.FinalCursorJson
		}
	}
	return nil
}

type isFetchEvent_Payload interface {
	isFetchEvent_Payload()
}

type FetchEvent_Item struct {
	Item *FetchedItem `protobuf:"bytes,1,opt,name=item,proto3,oneof"`
}

type FetchEvent_CheckpointCursorJson struct {
	CheckpointCursorJson []byte `protobuf:"bytes,2,opt,name=checkpoint_cursor_json,json=checkpointCursorJson,proto3,oneof"`
}

type FetchEvent_FinalCursorJson struct {
	FinalCursorJson []byte `protobuf:"bytes,3,opt,name=final_cursor_json,json=finalCursorJson,proto3,oneof"`
}

func (*FetchEvent_Item) isFetchEvent_Payload() {}

func (*FetchEvent_CheckpointCursorJson) isFetchEvent_Payload() {}

func (*FetchEvent_FinalCursorJson) isFetchEvent_Payload() {}

var File_plugin_proto_datasource_proto protoreflect.FileDescriptor

const file_plugin_proto_datasource_proto_rawDesc = "" +
	"\n" +
	"\x1dplugin/proto/datasource.proto\x12\x11weknora.plugin.v1\"\a\n" +
	"\x05Empty\"\x10\n" +
	"\x0eGetInfoRequest\"\x8d\x01\n" +
	"\x0fGetInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0econnector_type\x18\x04 \x01(\tR\rconnectorType\"0\n" +
	"\rConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"T\n" +
	"\x14ListResourcesRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"\xa1\x02\n" +
	"\bResource\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x123\n" +
	"\x16modified_at_unix_milli\x18\x06 \x01(\x03R\x13modifiedAtUnixMilli\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12!\n" +
	"\fhas_children\x18\b \x01(\bR\vhasChildren\x12#\n" +
	"\rmetadata_json\x18\t \x01(\fR\fmetadataJson\"R\n" +
	"\x15ListResourcesResponse\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.weknora.plugin.v1.ResourceR\tresources\"e\n" +
	"\x1fResolveResourceAncestorsRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\"O\n" +
	"\tAncestors\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fexternal_ids\x18\x02 \x03(\tR\vexternalIds\"^\n" +
	" ResolveResourceAncestorsResponse\x12:\n" +
	"\tancestors\x18\x01 \x03(\v2\x1c.weknora.plugin.v1.AncestorsR\tancestors\"\x87\x01\n" +
	"\fFetchRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x12\x1f\n" +
	"\vcursor_json\x18\x03 \x01(\fR\n" +
	"cursorJson\x12\x12\n" +
	"\x04full\x18\x04 \x01(\bR\x04full\"\x85\x04\n" +
	"\vFetchedItem\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x121\n" +
	"\x15updated_at_unix_milli\x18\a \x01(\x03R\x12updatedAtUnixMilli\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.weknora.plugin.v1.FetchedItem.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x12,\n" +
	"\x12source_resource_id\x18\n" +
	" \x01(\tR\x10sourceResourceId\x12)\n" +
	"\x10replaces_subtree\x18\v \x01(\bR\x0freplacesSubtree\x12!\n" +
	"\fsubtree_keep\x18\f \x03(\tR\vsubtreeKeep\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\n" +
	"FetchEvent\x124\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.weknora.plugin.v1.FetchedItemH\x00R\x04item\x126\n" +
	"\x16checkpoint_cursor_json\x18\x02 \x01(\fH\x00R\x14checkpointCursorJson\x12,\n" +
	"\x11final_cursor_json\x18\x03 \x01(\fH\x00R\x0ffinalCursorJsonB\t\n" +
	"\apayload2\xe1\x03\n" +
	"\x10DatasourcePlugin\x12P\n" +
	"\aGetInfo\x12!.weknora.plugin.v1.GetInfoRequest\x1a\".weknora.plugin.v1.GetInfoResponse\x12F\n" +
	"\bValidate\x12 .weknora.plugin.v1.ConfigRequest\x1a\x18.weknora.plugin.v1.Empty\x12b\n" +
	"\rListResources\x12'.weknora.plugin.v1.ListResourcesRequest\x1a(.weknora.plugin.v1.ListResourcesResponse\x12\x83\x01\n" +
	"\x18ResolveResourceAncestors\x122.weknora.plugin.v1.ResolveResourceAncestorsRequest\x1a3.weknora.plugin.v1.ResolveResourceAncestorsResponse\x12I\n" +
	"\x05Fetch\x12\x1f.weknora.plugin.v1.FetchRequest\x1a\x1d.weknora.plugin.v1.FetchEvent0\x01B5Z3github.com/Tencent/WeKnora/plugin/proto;pluginprotob\x06proto3"

var (
	file_plugin_proto_datasource_proto_rawDescOnce sync.Once
	file_plugin_proto_datasource_proto_rawDescData []byte
)

func file_plugin_proto_datasource_proto_rawDescGZIP() []byte {
	file_plugin_proto_datasource_proto_rawDescOnce.Do(func() {
		file_plugin_proto_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_datasource_proto_rawDesc), len(file_plugin_proto_datasource_proto_rawDesc)))
	})
	return file_plugin_proto_datasource_proto_rawDescData
}

var file_plugin_proto_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_plugin_proto_datasource_proto_goTypes = []any{
	(*Empty)(nil),                            // 0: weknora.plugin.v1.Empty
	(*GetInfoRequest)(nil),                   // 1: weknora.plugin.v1.GetInfoRequest
	(*GetInfoResponse)(nil),                  // 2: weknora.plugin.v1.GetInfoResponse
	(*ConfigRequest)(nil),                    // 3: weknora.plugin.v1.ConfigRequest
	(*ListResourcesRequest)(nil),             // 4: weknora.plugin.v1.ListResourcesRequest
	(*Resource)(nil),                         // 5: weknora.plugin.v1.Resource
	(*ListResourcesResponse)(nil),            // 6: weknora.plugin.v1.ListResourcesResponse
	(*ResolveResourceAncestorsRequest)(nil),  // 7: weknora.plugin.v1.ResolveResourceAncestorsRequest
	(*Ancestors)(nil),                        // 8: weknora.plugin.v1.Ancestors
	(*ResolveResourceAncestorsResponse)(nil), // 9: weknora.plugin.v1.ResolveResourceAncestorsResponse
	(*FetchRequest)(nil),                     // 10: weknora.plugin.v1.FetchRequest
	(*FetchedItem)(nil),                      // 11: weknora.plugin.v1.FetchedItem
	(*FetchEvent)(nil),                       // 12: weknora.plugin.v1.FetchEvent
	nil,                                      // 13: weknora.plugin.v1.FetchedItem.MetadataEntry
}
var file_plugin_proto_datasource_proto_depIdxs = []int32{
	5,  // 0: weknora.plugin.v1.ListResourcesResponse.resources:type_name -> weknora.plugin.v1.Resource
	8,  // 1: weknora.plugin.v1.ResolveResourceAncestorsResponse.ancestors:type_name -> weknora.plugin.v1.Ancestors
	13, // 2: weknora.plugin.v1.FetchedItem.metadata:type_name -> weknora.plugin.v1.FetchedItem.MetadataEntry
	11, // 3: weknora.plugin.v1.FetchEvent.item:type_name -> weknora.plugin.v1.FetchedItem
	1,  // 4: weknora.plugin.v1.DatasourcePlugin.GetInfo:input_type -> weknora.plugin.v1.GetInfoRequest
	3,  // 5: weknora.plugin.v1.DatasourcePlugin.Validate:input_type -> weknora.plugin.v1.ConfigRequest
	4,  // 6: weknora.plugin.v1.DatasourcePlugin.ListResources:input_type -> weknora.plugin.v1.ListResourcesRequest
	7,  // 7: weknora.plugin.v1.DatasourcePlugin.ResolveResourceAncestors:input_type -> weknora.plugin.v1.ResolveResourceAncestorsRequest
	10, // 8: weknora.plugin.v1.DatasourcePlugin.Fetch:input_type -> weknora.plugin.v1.FetchRequest
	2,  // 9: weknora.plugin.v1.DatasourcePlugin.GetInfo:output_type -> weknora.plugin.v1.GetInfoResponse
	0,  // 10: weknora.plugin.v1.DatasourcePlugin.Validate:output_type -> weknora.plugin.v1.Empty
	6,  // 11: weknora.plugin.v1.DatasourcePlugin.ListResources:output_type -> weknora.plugin.v1.ListResourcesResponse
	9,  // 12: weknora.plugin.v1.DatasourcePlugin.ResolveResourceAncestors:output_type -> weknora.plugin.v1.ResolveResourceAncestorsResponse
	12, // 13: weknora.plugin.v1.DatasourcePlugin.Fetch:output_type -> weknora.plugin.v1.FetchEvent
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_proto_datasource_proto_init() }
func file_plugin_proto_datasource_proto_init() {
	if File_plugin_proto_datasource_proto != nil {
		return
	}
	file_plugin_proto_datasource_proto_msgTypes[12].OneofWrappers = []any{
		(*FetchEvent_Item)(nil),
		(*FetchEvent_CheckpointCursorJson)(nil),
		(*FetchEvent_FinalCursorJson)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_datasource_proto_rawDesc), len(file_plugin_proto_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_datasource_proto_goTypes,
		DependencyIndexes: file_plugin_proto_datasource_proto_depIdxs,
		MessageInfos:      file_plugin_proto_datasource_proto_msgTypes,
	}.Build()
	File_plugin_proto_datasource_proto = out.File
	file_plugin_proto_datasource_proto_goTypes = nil
	file_plugin_proto_datasource_proto_depIdxs = nil
}
