// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: plugin/proto/document_parser.proto

package pluginproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	DocumentParserPlugin_GetInfo_FullMethodName = "/weknora.plugin.v1.DocumentParserPlugin/GetInfo"
	DocumentParserPlugin_Parse_FullMethodName   = "/weknora.plugin.v1.DocumentParserPlugin/Parse"
)

type DocumentParserPluginClient interface {
	GetInfo(context.Context, *DocumentParserInfoRequest, ...grpc.CallOption) (*DocumentParserInfoResponse, error)
	Parse(context.Context, *DocumentParseRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentParseFrame], error)
}

type documentParserPluginClient struct{ cc grpc.ClientConnInterface }

func NewDocumentParserPluginClient(cc grpc.ClientConnInterface) DocumentParserPluginClient {
	return &documentParserPluginClient{cc: cc}
}

func (c *documentParserPluginClient) GetInfo(ctx context.Context, in *DocumentParserInfoRequest, opts ...grpc.CallOption) (*DocumentParserInfoResponse, error) {
	out := new(DocumentParserInfoResponse)
	err := c.cc.Invoke(ctx, DocumentParserPlugin_GetInfo_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}

func (c *documentParserPluginClient) Parse(ctx context.Context, in *DocumentParseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentParseFrame], error) {
	stream, err := c.cc.NewStream(ctx, &DocumentParserPlugin_ServiceDesc.Streams[0], DocumentParserPlugin_Parse_FullMethodName, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	if err != nil {
		return nil, err
	}
	client := &grpc.GenericClientStream[DocumentParseRequest, DocumentParseFrame]{ClientStream: stream}
	if err := client.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := client.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return client, nil
}

type DocumentParserPlugin_ParseClient = grpc.ServerStreamingClient[DocumentParseFrame]

type DocumentParserPluginServer interface {
	GetInfo(context.Context, *DocumentParserInfoRequest) (*DocumentParserInfoResponse, error)
	Parse(*DocumentParseRequest, grpc.ServerStreamingServer[DocumentParseFrame]) error
	mustEmbedUnimplementedDocumentParserPluginServer()
}

type UnimplementedDocumentParserPluginServer struct{}

func (UnimplementedDocumentParserPluginServer) GetInfo(context.Context, *DocumentParserInfoRequest) (*DocumentParserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedDocumentParserPluginServer) Parse(*DocumentParseRequest, grpc.ServerStreamingServer[DocumentParseFrame]) error {
	return status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedDocumentParserPluginServer) mustEmbedUnimplementedDocumentParserPluginServer() {}
func (UnimplementedDocumentParserPluginServer) testEmbeddedByValue()                              {}

func RegisterDocumentParserPluginServer(s grpc.ServiceRegistrar, srv DocumentParserPluginServer) {
	if value, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		value.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentParserPlugin_ServiceDesc, srv)
}

func _DocumentParserPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentParserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserPluginServer).GetInfo(ctx, in)
	}
	return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: DocumentParserPlugin_GetInfo_FullMethodName}, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserPluginServer).GetInfo(ctx, req.(*DocumentParserInfoRequest))
	})
}

func _DocumentParserPlugin_Parse_Handler(srv interface{}, stream grpc.ServerStream) error {
	in := new(DocumentParseRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(DocumentParserPluginServer).Parse(in, &grpc.GenericServerStream[DocumentParseRequest, DocumentParseFrame]{ServerStream: stream})
}

type DocumentParserPlugin_ParseServer = grpc.ServerStreamingServer[DocumentParseFrame]

var DocumentParserPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DocumentParserPlugin",
	HandlerType: (*DocumentParserPluginServer)(nil),
	Methods: []grpc.MethodDesc{{
		MethodName: "GetInfo",
		Handler:    _DocumentParserPlugin_GetInfo_Handler,
	}},
	Streams: []grpc.StreamDesc{{
		StreamName:    "Parse",
		Handler:       _DocumentParserPlugin_Parse_Handler,
		ServerStreams: true,
	}},
	Metadata: "plugin/proto/document_parser.proto",
}
