// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: plugin/proto/document_parser.proto

package pluginproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentParserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentParserInfoRequest) Reset() {
	*x = DocumentParserInfoRequest{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParserInfoRequest) ProtoMessage() {}

func (x *DocumentParserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParserInfoRequest.ProtoReflect.Descriptor instead.
func (*DocumentParserInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{0}
}

type DocumentParserInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineName      string                 `protobuf:"bytes,4,opt,name=engine_name,json=engineName,proto3" json:"engine_name,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	FileTypes       []string               `protobuf:"bytes,6,rep,name=file_types,json=fileTypes,proto3" json:"file_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentParserInfoResponse) Reset() {
	*x = DocumentParserInfoResponse{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParserInfoResponse) ProtoMessage() {}

func (x *DocumentParserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParserInfoResponse.ProtoReflect.Descriptor instead.
func (*DocumentParserInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentParserInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentParserInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DocumentParserInfoResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *DocumentParserInfoResponse) GetEngineName() string {
	if x != nil {
		return x.EngineName
	}
	return ""
}

func (x *DocumentParserInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentParserInfoResponse) GetFileTypes() []string {
	if x != nil {
		return x.FileTypes
	}
	return nil
}

type DocumentParseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileContent     []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName        string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType        string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	RequestId       string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConfigOverrides map[string]string      `protobuf:"bytes,7,rep,name=config_overrides,json=configOverrides,proto3" json:"config_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentParseRequest) Reset() {
	*x = DocumentParseRequest{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParseRequest) ProtoMessage() {}

func (x *DocumentParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParseRequest.ProtoReflect.Descriptor instead.
func (*DocumentParseRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentParseRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *DocumentParseRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentParseRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *DocumentParseRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocumentParseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentParseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DocumentParseRequest) GetConfigOverrides() map[string]string {
	if x != nil {
		return x.ConfigOverrides
	}
	return nil
}

type DocumentParseMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarkdownContent string                 `protobuf:"bytes,1,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`
	ImageDirPath    string                 `protobuf:"bytes,2,opt,name=image_dir_path,json=imageDirPath,proto3" json:"image_dir_path,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	IsAudio         bool                   `protobuf:"varint,5,opt,name=is_audio,json=isAudio,proto3" json:"is_audio,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentParseMeta) Reset() {
	*x = DocumentParseMeta{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParseMeta) ProtoMessage() {}

func (x *DocumentParseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParseMeta.ProtoReflect.Descriptor instead.
func (*DocumentParseMeta) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentParseMeta) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *DocumentParseMeta) GetImageDirPath() string {
	if x != nil {
		return x.ImageDirPath
	}
	return ""
}

func (x *DocumentParseMeta) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentParseMeta) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DocumentParseMeta) GetIsAudio() bool {
	if x != nil {
		return x.IsAudio
	}
	return false
}

type DocumentImageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalRef   string                 `protobuf:"bytes,2,opt,name=original_ref,json=originalRef,proto3" json:"original_ref,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	StorageKey    string                 `protobuf:"bytes,4,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,5,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	IsOriginal    bool                   `protobuf:"varint,6,opt,name=is_original,json=isOriginal,proto3" json:"is_original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentImageRef) Reset() {
	*x = DocumentImageRef{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentImageRef) ProtoMessage() {}

func (x *DocumentImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentImageRef.ProtoReflect.Descriptor instead.
func (*DocumentImageRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentImageRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentImageRef) GetOriginalRef() string {
	if x != nil {
		return x.OriginalRef
	}
	return ""
}

func (x *DocumentImageRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocumentImageRef) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *DocumentImageRef) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *DocumentImageRef) GetIsOriginal() bool {
	if x != nil {
		return x.IsOriginal
	}
	return false
}

type DocumentAudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentAudioChunk) Reset() {
	*x = DocumentAudioChunk{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentAudioChunk) ProtoMessage() {}

func (x *DocumentAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentAudioChunk.ProtoReflect.Descriptor instead.
func (*DocumentAudioChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentAudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DocumentParseFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DocumentParseFrame_Meta
	//	*DocumentParseFrame_Image
	//	*DocumentParseFrame_Audio
	Payload       isDocumentParseFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentParseFrame) Reset() {
	*x = DocumentParseFrame{}
	mi := &file_plugin_proto_document_parser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParseFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParseFrame) ProtoMessage() {}

func (x *DocumentParseFrame) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_document_parser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParseFrame.ProtoReflect.Descriptor instead.
func (*DocumentParseFrame) Descriptor() ([]byte, []int) {
	return file_plugin_proto_document_parser_proto_rawDescGZIP(), []int{6}
}

func (x *DocumentParseFrame) GetPayload() isDocumentParseFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DocumentParseFrame) GetMeta() *DocumentParseMeta {
	if x != nil {
		if x, ok := x.Payload.(*DocumentParseFrame_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *DocumentParseFrame) GetImage() *DocumentImageRef {
	if x != nil {
		if x, ok := x.Payload.(*DocumentParseFrame_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *DocumentParseFrame) GetAudio() *DocumentAudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*DocumentParseFrame_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isDocumentParseFrame_Payload interface {
	isDocumentParseFrame_Payload()
}

type DocumentParseFrame_Meta struct {
	Meta *DocumentParseMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type DocumentParseFrame_Image struct {
	Image *DocumentImageRef `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type DocumentParseFrame_Audio struct {
	Audio *DocumentAudioChunk `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

func (*DocumentParseFrame_Meta) isDocumentParseFrame_Payload() {}

func (*DocumentParseFrame_Image) isDocumentParseFrame_Payload() {}

func (*DocumentParseFrame_Audio) isDocumentParseFrame_Payload() {}

var File_plugin_proto_document_parser_proto protoreflect.FileDescriptor

const file_plugin_proto_document_parser_proto_rawDesc = "" +
	"\n" +
	"\"plugin/proto/document_parser.proto\x12\x11weknora.plugin.v1\"\x1b\n" +
	"\x19DocumentParserInfoRequest\"\xd3\x01\n" +
	"\x1aDocumentParserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vengine_name\x18\x04 \x01(\tR\n" +
	"engineName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"file_types\x18\x06 \x03(\tR\tfileTypes\"\xe7\x02\n" +
	"\x14DocumentParseRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12g\n" +
	"\x10config_overrides\x18\a \x03(\v2<.weknora.plugin.v1.DocumentParseRequest.ConfigOverridesEntryR\x0fconfigOverrides\x1aB\n" +
	"\x14ConfigOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\x11DocumentParseMeta\x12)\n" +
	"\x10markdown_content\x18\x01 \x01(\tR\x0fmarkdownContent\x12$\n" +
	"\x0eimage_dir_path\x18\x02 \x01(\tR\fimageDirPath\x12N\n" +
	"\bmetadata\x18\x03 \x03(\v22.weknora.plugin.v1.DocumentParseMeta.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x19\n" +
	"\bis_audio\x18\x05 \x01(\bR\aisAudio\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x10DocumentImageRef\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\foriginal_ref\x18\x02 \x01(\tR\voriginalRef\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vstorage_key\x18\x04 \x01(\tR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"image_data\x18\x05 \x01(\fR\timageData\x12\x1f\n" +
	"\vis_original\x18\x06 \x01(\bR\n" +
	"isOriginal\"(\n" +
	"\x12DocumentAudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xd7\x01\n" +
	"\x12DocumentParseFrame\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2$.weknora.plugin.v1.DocumentParseMetaH\x00R\x04meta\x12;\n" +
	"\x05image\x18\x02 \x01(\v2#.weknora.plugin.v1.DocumentImageRefH\x00R\x05image\x12=\n" +
	"\x05audio\x18\x03 \x01(\v2%.weknora.plugin.v1.DocumentAudioChunkH\x00R\x05audioB\t\n" +
	"\apayload2\xd9\x01\n" +
	"\x14DocumentParserPlugin\x12f\n" +
	"\aGetInfo\x12,.weknora.plugin.v1.DocumentParserInfoRequest\x1a-.weknora.plugin.v1.DocumentParserInfoResponse\x12Y\n" +
	"\x05Parse\x12'.weknora.plugin.v1.DocumentParseRequest\x1a%.weknora.plugin.v1.DocumentParseFrame0\x01B5Z3github.com/Tencent/WeKnora/plugin/proto;pluginprotob\x06proto3"

var (
	file_plugin_proto_document_parser_proto_rawDescOnce sync.Once
	file_plugin_proto_document_parser_proto_rawDescData []byte
)

func file_plugin_proto_document_parser_proto_rawDescGZIP() []byte {
	file_plugin_proto_document_parser_proto_rawDescOnce.Do(func() {
		file_plugin_proto_document_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_document_parser_proto_rawDesc), len(file_plugin_proto_document_parser_proto_rawDesc)))
	})
	return file_plugin_proto_document_parser_proto_rawDescData
}

var file_plugin_proto_document_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_proto_document_parser_proto_goTypes = []any{
	(*DocumentParserInfoRequest)(nil),  // 0: weknora.plugin.v1.DocumentParserInfoRequest
	(*DocumentParserInfoResponse)(nil), // 1: weknora.plugin.v1.DocumentParserInfoResponse
	(*DocumentParseRequest)(nil),       // 2: weknora.plugin.v1.DocumentParseRequest
	(*DocumentParseMeta)(nil),          // 3: weknora.plugin.v1.DocumentParseMeta
	(*DocumentImageRef)(nil),           // 4: weknora.plugin.v1.DocumentImageRef
	(*DocumentAudioChunk)(nil),         // 5: weknora.plugin.v1.DocumentAudioChunk
	(*DocumentParseFrame)(nil),         // 6: weknora.plugin.v1.DocumentParseFrame
	nil,                                // 7: weknora.plugin.v1.DocumentParseRequest.ConfigOverridesEntry
	nil,                                // 8: weknora.plugin.v1.DocumentParseMeta.MetadataEntry
}
var file_plugin_proto_document_parser_proto_depIdxs = []int32{
	7, // 0: weknora.plugin.v1.DocumentParseRequest.config_overrides:type_name -> weknora.plugin.v1.DocumentParseRequest.ConfigOverridesEntry
	8, // 1: weknora.plugin.v1.DocumentParseMeta.metadata:type_name -> weknora.plugin.v1.DocumentParseMeta.MetadataEntry
	3, // 2: weknora.plugin.v1.DocumentParseFrame.meta:type_name -> weknora.plugin.v1.DocumentParseMeta
	4, // 3: weknora.plugin.v1.DocumentParseFrame.image:type_name -> weknora.plugin.v1.DocumentImageRef
	5, // 4: weknora.plugin.v1.DocumentParseFrame.audio:type_name -> weknora.plugin.v1.DocumentAudioChunk
	0, // 5: weknora.plugin.v1.DocumentParserPlugin.GetInfo:input_type -> weknora.plugin.v1.DocumentParserInfoRequest
	2, // 6: weknora.plugin.v1.DocumentParserPlugin.Parse:input_type -> weknora.plugin.v1.DocumentParseRequest
	1, // 7: weknora.plugin.v1.DocumentParserPlugin.GetInfo:output_type -> weknora.plugin.v1.DocumentParserInfoResponse
	6, // 8: weknora.plugin.v1.DocumentParserPlugin.Parse:output_type -> weknora.plugin.v1.DocumentParseFrame
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_plugin_proto_document_parser_proto_init() }
func file_plugin_proto_document_parser_proto_init() {
	if File_plugin_proto_document_parser_proto != nil {
		return
	}
	file_plugin_proto_document_parser_proto_msgTypes[6].OneofWrappers = []any{
		(*DocumentParseFrame_Meta)(nil),
		(*DocumentParseFrame_Image)(nil),
		(*DocumentParseFrame_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_document_parser_proto_rawDesc), len(file_plugin_proto_document_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_document_parser_proto_goTypes,
		DependencyIndexes: file_plugin_proto_document_parser_proto_depIdxs,
		MessageInfos:      file_plugin_proto_document_parser_proto_msgTypes,
	}.Build()
	File_plugin_proto_document_parser_proto = out.File
	file_plugin_proto_document_parser_proto_goTypes = nil
	file_plugin_proto_document_parser_proto_depIdxs = nil
}
