// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: plugin/proto/model_provider.proto

package pluginproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelProviderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProviderInfoRequest) Reset() {
	*x = ModelProviderInfoRequest{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderInfoRequest) ProtoMessage() {}

func (x *ModelProviderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelProviderInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{0}
}

type ModelProviderConfigOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProviderConfigOption) Reset() {
	*x = ModelProviderConfigOption{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderConfigOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderConfigOption) ProtoMessage() {}

func (x *ModelProviderConfigOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderConfigOption.ProtoReflect.Descriptor instead.
func (*ModelProviderConfigOption) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ModelProviderConfigOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ModelProviderConfigOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ModelProviderConfigField struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Key           string                       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                       `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                         `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                       `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Placeholder   string                       `protobuf:"bytes,6,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Options       []*ModelProviderConfigOption `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProviderConfigField) Reset() {
	*x = ModelProviderConfigField{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderConfigField) ProtoMessage() {}

func (x *ModelProviderConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderConfigField.ProtoReflect.Descriptor instead.
func (*ModelProviderConfigField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ModelProviderConfigField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModelProviderConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ModelProviderConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ModelProviderConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ModelProviderConfigField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ModelProviderConfigField) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *ModelProviderConfigField) GetOptions() []*ModelProviderConfigOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ModelProviderInfoResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Id              string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                      `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion string                      `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ProviderName    string                      `protobuf:"bytes,4,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	DisplayName     string                      `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                      `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	DefaultUrls     map[string]string           `protobuf:"bytes,7,rep,name=default_urls,json=defaultUrls,proto3" json:"default_urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModelTypes      []string                    `protobuf:"bytes,8,rep,name=model_types,json=modelTypes,proto3" json:"model_types,omitempty"`
	RequiresAuth    bool                        `protobuf:"varint,9,opt,name=requires_auth,json=requiresAuth,proto3" json:"requires_auth,omitempty"`
	ExtraFields     []*ModelProviderConfigField `protobuf:"bytes,10,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	Transport       string                      `protobuf:"bytes,11,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelProviderInfoResponse) Reset() {
	*x = ModelProviderInfoResponse{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderInfoResponse) ProtoMessage() {}

func (x *ModelProviderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelProviderInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ModelProviderInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelProviderInfoResponse) GetDefaultUrls() map[string]string {
	if x != nil {
		return x.DefaultUrls
	}
	return nil
}

func (x *ModelProviderInfoResponse) GetModelTypes() []string {
	if x != nil {
		return x.ModelTypes
	}
	return nil
}

func (x *ModelProviderInfoResponse) GetRequiresAuth() bool {
	if x != nil {
		return x.RequiresAuth
	}
	return false
}

func (x *ModelProviderInfoResponse) GetExtraFields() []*ModelProviderConfigField {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

func (x *ModelProviderInfoResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type ModelProviderValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProviderValidateRequest) Reset() {
	*x = ModelProviderValidateRequest{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderValidateRequest) ProtoMessage() {}

func (x *ModelProviderValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderValidateRequest.ProtoReflect.Descriptor instead.
func (*ModelProviderValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ModelProviderValidateRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ModelProviderValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProviderValidateResponse) Reset() {
	*x = ModelProviderValidateResponse{}
	mi := &file_plugin_proto_model_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProviderValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProviderValidateResponse) ProtoMessage() {}

func (x *ModelProviderValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_model_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProviderValidateResponse.ProtoReflect.Descriptor instead.
func (*ModelProviderValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_model_provider_proto_rawDescGZIP(), []int{5}
}

var File_plugin_proto_model_provider_proto protoreflect.FileDescriptor

const file_plugin_proto_model_provider_proto_rawDesc = "" +
	"\n" +
	"!plugin/proto/model_provider.proto\x12\x11weknora.plugin.v1\"\x1a\n" +
	"\x18ModelProviderInfoRequest\"G\n" +
	"\x19ModelProviderConfigOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x81\x02\n" +
	"\x18ModelProviderConfigField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12 \n" +
	"\vplaceholder\x18\x06 \x01(\tR\vplaceholder\x12F\n" +
	"\aoptions\x18\a \x03(\v2,.weknora.plugin.v1.ModelProviderConfigOptionR\aoptions\"\xb0\x04\n" +
	"\x19ModelProviderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\rprovider_name\x18\x04 \x01(\tR\fproviderName\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12`\n" +
	"\fdefault_urls\x18\a \x03(\v2=.weknora.plugin.v1.ModelProviderInfoResponse.DefaultUrlsEntryR\vdefaultUrls\x12\x1f\n" +
	"\vmodel_types\x18\b \x03(\tR\n" +
	"modelTypes\x12#\n" +
	"\rrequires_auth\x18\t \x01(\bR\frequiresAuth\x12N\n" +
	"\fextra_fields\x18\n" +
	" \x03(\v2+.weknora.plugin.v1.ModelProviderConfigFieldR\vextraFields\x12\x1c\n" +
	"\ttransport\x18\v \x01(\tR\ttransport\x1a>\n" +
	"\x10DefaultUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x1cModelProviderValidateRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"\x1f\n" +
	"\x1dModelProviderValidateResponse2\xf0\x01\n" +
	"\x13ModelProviderPlugin\x12d\n" +
	"\aGetInfo\x12+.weknora.plugin.v1.ModelProviderInfoRequest\x1a,.weknora.plugin.v1.ModelProviderInfoResponse\x12s\n" +
	"\x0eValidateConfig\x12/.weknora.plugin.v1.ModelProviderValidateRequest\x1a0.weknora.plugin.v1.ModelProviderValidateResponseB5Z3github.com/Tencent/WeKnora/plugin/proto;pluginprotob\x06proto3"

var (
	file_plugin_proto_model_provider_proto_rawDescOnce sync.Once
	file_plugin_proto_model_provider_proto_rawDescData []byte
)

func file_plugin_proto_model_provider_proto_rawDescGZIP() []byte {
	file_plugin_proto_model_provider_proto_rawDescOnce.Do(func() {
		file_plugin_proto_model_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_model_provider_proto_rawDesc), len(file_plugin_proto_model_provider_proto_rawDesc)))
	})
	return file_plugin_proto_model_provider_proto_rawDescData
}

var file_plugin_proto_model_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_proto_model_provider_proto_goTypes = []any{
	(*ModelProviderInfoRequest)(nil),      // 0: weknora.plugin.v1.ModelProviderInfoRequest
	(*ModelProviderConfigOption)(nil),     // 1: weknora.plugin.v1.ModelProviderConfigOption
	(*ModelProviderConfigField)(nil),      // 2: weknora.plugin.v1.ModelProviderConfigField
	(*ModelProviderInfoResponse)(nil),     // 3: weknora.plugin.v1.ModelProviderInfoResponse
	(*ModelProviderValidateRequest)(nil),  // 4: weknora.plugin.v1.ModelProviderValidateRequest
	(*ModelProviderValidateResponse)(nil), // 5: weknora.plugin.v1.ModelProviderValidateResponse
	nil,                                   // 6: weknora.plugin.v1.ModelProviderInfoResponse.DefaultUrlsEntry
}
var file_plugin_proto_model_provider_proto_depIdxs = []int32{
	1, // 0: weknora.plugin.v1.ModelProviderConfigField.options:type_name -> weknora.plugin.v1.ModelProviderConfigOption
	6, // 1: weknora.plugin.v1.ModelProviderInfoResponse.default_urls:type_name -> weknora.plugin.v1.ModelProviderInfoResponse.DefaultUrlsEntry
	2, // 2: weknora.plugin.v1.ModelProviderInfoResponse.extra_fields:type_name -> weknora.plugin.v1.ModelProviderConfigField
	0, // 3: weknora.plugin.v1.ModelProviderPlugin.GetInfo:input_type -> weknora.plugin.v1.ModelProviderInfoRequest
	4, // 4: weknora.plugin.v1.ModelProviderPlugin.ValidateConfig:input_type -> weknora.plugin.v1.ModelProviderValidateRequest
	3, // 5: weknora.plugin.v1.ModelProviderPlugin.GetInfo:output_type -> weknora.plugin.v1.ModelProviderInfoResponse
	5, // 6: weknora.plugin.v1.ModelProviderPlugin.ValidateConfig:output_type -> weknora.plugin.v1.ModelProviderValidateResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_proto_model_provider_proto_init() }
func file_plugin_proto_model_provider_proto_init() {
	if File_plugin_proto_model_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_model_provider_proto_rawDesc), len(file_plugin_proto_model_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_model_provider_proto_goTypes,
		DependencyIndexes: file_plugin_proto_model_provider_proto_depIdxs,
		MessageInfos:      file_plugin_proto_model_provider_proto_msgTypes,
	}.Build()
	File_plugin_proto_model_provider_proto = out.File
	file_plugin_proto_model_provider_proto_goTypes = nil
	file_plugin_proto_model_provider_proto_depIdxs = nil
}
