// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: plugin/proto/model_provider.proto

package pluginproto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	ModelProviderPlugin_GetInfo_FullMethodName        = "/weknora.plugin.v1.ModelProviderPlugin/GetInfo"
	ModelProviderPlugin_ValidateConfig_FullMethodName = "/weknora.plugin.v1.ModelProviderPlugin/ValidateConfig"
)

type ModelProviderPluginClient interface {
	GetInfo(context.Context, *ModelProviderInfoRequest, ...grpc.CallOption) (*ModelProviderInfoResponse, error)
	ValidateConfig(context.Context, *ModelProviderValidateRequest, ...grpc.CallOption) (*ModelProviderValidateResponse, error)
}

type modelProviderPluginClient struct{ cc grpc.ClientConnInterface }

func NewModelProviderPluginClient(cc grpc.ClientConnInterface) ModelProviderPluginClient {
	return &modelProviderPluginClient{cc: cc}
}
func (c *modelProviderPluginClient) GetInfo(ctx context.Context, in *ModelProviderInfoRequest, opts ...grpc.CallOption) (*ModelProviderInfoResponse, error) {
	out := new(ModelProviderInfoResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_GetInfo_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *modelProviderPluginClient) ValidateConfig(ctx context.Context, in *ModelProviderValidateRequest, opts ...grpc.CallOption) (*ModelProviderValidateResponse, error) {
	out := new(ModelProviderValidateResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_ValidateConfig_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}

type ModelProviderPluginServer interface {
	GetInfo(context.Context, *ModelProviderInfoRequest) (*ModelProviderInfoResponse, error)
	ValidateConfig(context.Context, *ModelProviderValidateRequest) (*ModelProviderValidateResponse, error)
	mustEmbedUnimplementedModelProviderPluginServer()
}
type UnimplementedModelProviderPluginServer struct{}

func (UnimplementedModelProviderPluginServer) GetInfo(context.Context, *ModelProviderInfoRequest) (*ModelProviderInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedModelProviderPluginServer) ValidateConfig(context.Context, *ModelProviderValidateRequest) (*ModelProviderValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedModelProviderPluginServer) mustEmbedUnimplementedModelProviderPluginServer() {}
func (UnimplementedModelProviderPluginServer) testEmbeddedByValue()                             {}

func RegisterModelProviderPluginServer(s grpc.ServiceRegistrar, srv ModelProviderPluginServer) {
	if value, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		value.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProviderPlugin_ServiceDesc, srv)
}

func modelProviderUnary[Req any](method, fullMethod string, allocate func() *Req, call func(ModelProviderPluginServer, context.Context, *Req) (interface{}, error)) grpc.MethodDesc {
	return grpc.MethodDesc{MethodName: method, Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
		in := allocate()
		if err := dec(in); err != nil {
			return nil, err
		}
		if interceptor == nil {
			return call(srv.(ModelProviderPluginServer), ctx, in)
		}
		return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: fullMethod}, func(ctx context.Context, req interface{}) (interface{}, error) {
			return call(srv.(ModelProviderPluginServer), ctx, req.(*Req))
		})
	}}
}

var ModelProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.ModelProviderPlugin",
	HandlerType: (*ModelProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		modelProviderUnary("GetInfo", ModelProviderPlugin_GetInfo_FullMethodName, func() *ModelProviderInfoRequest { return new(ModelProviderInfoRequest) }, func(s ModelProviderPluginServer, c context.Context, r *ModelProviderInfoRequest) (interface{}, error) {
			return s.GetInfo(c, r)
		}),
		modelProviderUnary("ValidateConfig", ModelProviderPlugin_ValidateConfig_FullMethodName, func() *ModelProviderValidateRequest { return new(ModelProviderValidateRequest) }, func(s ModelProviderPluginServer, c context.Context, r *ModelProviderValidateRequest) (interface{}, error) {
			return s.ValidateConfig(c, r)
		}),
	},
	Metadata: "plugin/proto/model_provider.proto",
}
