// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: plugin/proto/web_search.proto

package pluginproto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	WebSearchPlugin_GetInfo_FullMethodName = "/weknora.plugin.v1.WebSearchPlugin/GetInfo"
	WebSearchPlugin_Search_FullMethodName  = "/weknora.plugin.v1.WebSearchPlugin/Search"
)

type WebSearchPluginClient interface {
	GetInfo(context.Context, *WebSearchInfoRequest, ...grpc.CallOption) (*WebSearchInfoResponse, error)
	Search(context.Context, *WebSearchRequest, ...grpc.CallOption) (*WebSearchResponse, error)
}

type webSearchPluginClient struct{ cc grpc.ClientConnInterface }

func NewWebSearchPluginClient(cc grpc.ClientConnInterface) WebSearchPluginClient {
	return &webSearchPluginClient{cc: cc}
}
func (c *webSearchPluginClient) GetInfo(ctx context.Context, in *WebSearchInfoRequest, opts ...grpc.CallOption) (*WebSearchInfoResponse, error) {
	out := new(WebSearchInfoResponse)
	err := c.cc.Invoke(ctx, WebSearchPlugin_GetInfo_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *webSearchPluginClient) Search(ctx context.Context, in *WebSearchRequest, opts ...grpc.CallOption) (*WebSearchResponse, error) {
	out := new(WebSearchResponse)
	err := c.cc.Invoke(ctx, WebSearchPlugin_Search_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}

type WebSearchPluginServer interface {
	GetInfo(context.Context, *WebSearchInfoRequest) (*WebSearchInfoResponse, error)
	Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error)
	mustEmbedUnimplementedWebSearchPluginServer()
}
type UnimplementedWebSearchPluginServer struct{}

func (UnimplementedWebSearchPluginServer) GetInfo(context.Context, *WebSearchInfoRequest) (*WebSearchInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedWebSearchPluginServer) Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWebSearchPluginServer) mustEmbedUnimplementedWebSearchPluginServer() {}
func (UnimplementedWebSearchPluginServer) testEmbeddedByValue()                         {}

func RegisterWebSearchPluginServer(s grpc.ServiceRegistrar, srv WebSearchPluginServer) {
	if value, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		value.testEmbeddedByValue()
	}
	s.RegisterService(&WebSearchPlugin_ServiceDesc, srv)
}

func webSearchUnary[Req any](method string, allocate func() *Req, call func(WebSearchPluginServer, context.Context, *Req) (interface{}, error)) grpc.MethodDesc {
	return grpc.MethodDesc{MethodName: method, Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
		in := allocate()
		if err := dec(in); err != nil {
			return nil, err
		}
		if interceptor == nil {
			return call(srv.(WebSearchPluginServer), ctx, in)
		}
		fullMethod := WebSearchPlugin_Search_FullMethodName
		if method == "GetInfo" {
			fullMethod = WebSearchPlugin_GetInfo_FullMethodName
		}
		return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: fullMethod}, func(ctx context.Context, req interface{}) (interface{}, error) {
			return call(srv.(WebSearchPluginServer), ctx, req.(*Req))
		})
	}}
}

var WebSearchPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.WebSearchPlugin",
	HandlerType: (*WebSearchPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		webSearchUnary("GetInfo", func() *WebSearchInfoRequest { return new(WebSearchInfoRequest) }, func(s WebSearchPluginServer, c context.Context, r *WebSearchInfoRequest) (interface{}, error) {
			return s.GetInfo(c, r)
		}),
		webSearchUnary("Search", func() *WebSearchRequest { return new(WebSearchRequest) }, func(s WebSearchPluginServer, c context.Context, r *WebSearchRequest) (interface{}, error) {
			return s.Search(c, r)
		}),
	},
	Metadata: "plugin/proto/web_search.proto",
}
