// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: plugin/proto/web_search.proto

package pluginproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSearchInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchInfoRequest) Reset() {
	*x = WebSearchInfoRequest{}
	mi := &file_plugin_proto_web_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchInfoRequest) ProtoMessage() {}

func (x *WebSearchInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_web_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchInfoRequest.ProtoReflect.Descriptor instead.
func (*WebSearchInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_web_search_proto_rawDescGZIP(), []int{0}
}

type WebSearchInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ProviderType    string                 `protobuf:"bytes,4,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebSearchInfoResponse) Reset() {
	*x = WebSearchInfoResponse{}
	mi := &file_plugin_proto_web_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchInfoResponse) ProtoMessage() {}

func (x *WebSearchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_web_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchInfoResponse.ProtoReflect.Descriptor instead.
func (*WebSearchInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_web_search_proto_rawDescGZIP(), []int{1}
}

func (x *WebSearchInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebSearchInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebSearchInfoResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *WebSearchInfoResponse) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

type WebSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParametersJson []byte                 `protobuf:"bytes,1,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults     int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	IncludeDate    bool                   `protobuf:"varint,4,opt,name=include_date,json=includeDate,proto3" json:"include_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebSearchRequest) Reset() {
	*x = WebSearchRequest{}
	mi := &file_plugin_proto_web_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchRequest) ProtoMessage() {}

func (x *WebSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_web_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchRequest.ProtoReflect.Descriptor instead.
func (*WebSearchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_web_search_proto_rawDescGZIP(), []int{2}
}

func (x *WebSearchRequest) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *WebSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *WebSearchRequest) GetIncludeDate() bool {
	if x != nil {
		return x.IncludeDate
	}
	return false
}

type WebSearchResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Title                string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Snippet              string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Content              string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Source               string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	PublishedAtUnixMilli int64                  `protobuf:"varint,6,opt,name=published_at_unix_milli,json=publishedAtUnixMilli,proto3" json:"published_at_unix_milli,omitempty"`
	HasPublishedAt       bool                   `protobuf:"varint,7,opt,name=has_published_at,json=hasPublishedAt,proto3" json:"has_published_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WebSearchResult) Reset() {
	*x = WebSearchResult{}
	mi := &file_plugin_proto_web_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchResult) ProtoMessage() {}

func (x *WebSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_web_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchResult.ProtoReflect.Descriptor instead.
func (*WebSearchResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_web_search_proto_rawDescGZIP(), []int{3}
}

func (x *WebSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WebSearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebSearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *WebSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebSearchResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WebSearchResult) GetPublishedAtUnixMilli() int64 {
	if x != nil {
		return x.PublishedAtUnixMilli
	}
	return 0
}

func (x *WebSearchResult) GetHasPublishedAt() bool {
	if x != nil {
		return x.HasPublishedAt
	}
	return false
}

type WebSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*WebSearchResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchResponse) Reset() {
	*x = WebSearchResponse{}
	mi := &file_plugin_proto_web_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchResponse) ProtoMessage() {}

func (x *WebSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_web_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchResponse.ProtoReflect.Descriptor instead.
func (*WebSearchResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_web_search_proto_rawDescGZIP(), []int{4}
}

func (x *WebSearchResponse) GetResults() []*WebSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_plugin_proto_web_search_proto protoreflect.FileDescriptor

const file_plugin_proto_web_search_proto_rawDesc = "" +
	"\n" +
	"\x1dplugin/proto/web_search.proto\x12\x11weknora.plugin.v1\"\x16\n" +
	"\x14WebSearchInfoRequest\"\x91\x01\n" +
	"\x15WebSearchInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\rprovider_type\x18\x04 \x01(\tR\fproviderType\"\x95\x01\n" +
	"\x10WebSearchRequest\x12'\n" +
	"\x0fparameters_json\x18\x01 \x01(\fR\x0eparametersJson\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\x12!\n" +
	"\finclude_date\x18\x04 \x01(\bR\vincludeDate\"\xe6\x01\n" +
	"\x0fWebSearchResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x125\n" +
	"\x17published_at_unix_milli\x18\x06 \x01(\x03R\x14publishedAtUnixMilli\x12(\n" +
	"\x10has_published_at\x18\a \x01(\bR\x0ehasPublishedAt\"Q\n" +
	"\x11WebSearchResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".weknora.plugin.v1.WebSearchResultR\aresults2\xc4\x01\n" +
	"\x0fWebSearchPlugin\x12\\\n" +
	"\aGetInfo\x12'.weknora.plugin.v1.WebSearchInfoRequest\x1a(.weknora.plugin.v1.WebSearchInfoResponse\x12S\n" +
	"\x06Search\x12#.weknora.plugin.v1.WebSearchRequest\x1a$.weknora.plugin.v1.WebSearchResponseB5Z3github.com/Tencent/WeKnora/plugin/proto;pluginprotob\x06proto3"

var (
	file_plugin_proto_web_search_proto_rawDescOnce sync.Once
	file_plugin_proto_web_search_proto_rawDescData []byte
)

func file_plugin_proto_web_search_proto_rawDescGZIP() []byte {
	file_plugin_proto_web_search_proto_rawDescOnce.Do(func() {
		file_plugin_proto_web_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_web_search_proto_rawDesc), len(file_plugin_proto_web_search_proto_rawDesc)))
	})
	return file_plugin_proto_web_search_proto_rawDescData
}

var file_plugin_proto_web_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_proto_web_search_proto_goTypes = []any{
	(*WebSearchInfoRequest)(nil),  // 0: weknora.plugin.v1.WebSearchInfoRequest
	(*WebSearchInfoResponse)(nil), // 1: weknora.plugin.v1.WebSearchInfoResponse
	(*WebSearchRequest)(nil),      // 2: weknora.plugin.v1.WebSearchRequest
	(*WebSearchResult)(nil),       // 3: weknora.plugin.v1.WebSearchResult
	(*WebSearchResponse)(nil),     // 4: weknora.plugin.v1.WebSearchResponse
}
var file_plugin_proto_web_search_proto_depIdxs = []int32{
	3, // 0: weknora.plugin.v1.WebSearchResponse.results:type_name -> weknora.plugin.v1.WebSearchResult
	0, // 1: weknora.plugin.v1.WebSearchPlugin.GetInfo:input_type -> weknora.plugin.v1.WebSearchInfoRequest
	2, // 2: weknora.plugin.v1.WebSearchPlugin.Search:input_type -> weknora.plugin.v1.WebSearchRequest
	1, // 3: weknora.plugin.v1.WebSearchPlugin.GetInfo:output_type -> weknora.plugin.v1.WebSearchInfoResponse
	4, // 4: weknora.plugin.v1.WebSearchPlugin.Search:output_type -> weknora.plugin.v1.WebSearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_proto_web_search_proto_init() }
func file_plugin_proto_web_search_proto_init() {
	if File_plugin_proto_web_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_web_search_proto_rawDesc), len(file_plugin_proto_web_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_web_search_proto_goTypes,
		DependencyIndexes: file_plugin_proto_web_search_proto_depIdxs,
		MessageInfos:      file_plugin_proto_web_search_proto_msgTypes,
	}.Build()
	File_plugin_proto_web_search_proto = out.File
	file_plugin_proto_web_search_proto_goTypes = nil
	file_plugin_proto_web_search_proto_depIdxs = nil
}
