// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: plugin/proto/datasource.proto

package pluginproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	DatasourcePlugin_GetInfo_FullMethodName                  = "/weknora.plugin.v1.DatasourcePlugin/GetInfo"
	DatasourcePlugin_Validate_FullMethodName                 = "/weknora.plugin.v1.DatasourcePlugin/Validate"
	DatasourcePlugin_ListResources_FullMethodName            = "/weknora.plugin.v1.DatasourcePlugin/ListResources"
	DatasourcePlugin_ResolveResourceAncestors_FullMethodName = "/weknora.plugin.v1.DatasourcePlugin/ResolveResourceAncestors"
	DatasourcePlugin_Fetch_FullMethodName                    = "/weknora.plugin.v1.DatasourcePlugin/Fetch"
)

type DatasourcePluginClient interface {
	GetInfo(context.Context, *GetInfoRequest, ...grpc.CallOption) (*GetInfoResponse, error)
	Validate(context.Context, *ConfigRequest, ...grpc.CallOption) (*Empty, error)
	ListResources(context.Context, *ListResourcesRequest, ...grpc.CallOption) (*ListResourcesResponse, error)
	ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest, ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error)
	Fetch(context.Context, *FetchRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[FetchEvent], error)
}

type datasourcePluginClient struct{ cc grpc.ClientConnInterface }

func NewDatasourcePluginClient(cc grpc.ClientConnInterface) DatasourcePluginClient {
	return &datasourcePluginClient{cc: cc}
}

func (c *datasourcePluginClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, DatasourcePlugin_GetInfo_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *datasourcePluginClient) Validate(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, DatasourcePlugin_Validate_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *datasourcePluginClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, DatasourcePlugin_ListResources_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *datasourcePluginClient) ResolveResourceAncestors(ctx context.Context, in *ResolveResourceAncestorsRequest, opts ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error) {
	out := new(ResolveResourceAncestorsResponse)
	err := c.cc.Invoke(ctx, DatasourcePlugin_ResolveResourceAncestors_FullMethodName, in, out, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	return out, err
}
func (c *datasourcePluginClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchEvent], error) {
	stream, err := c.cc.NewStream(ctx, &DatasourcePlugin_ServiceDesc.Streams[0], DatasourcePlugin_Fetch_FullMethodName, append([]grpc.CallOption{grpc.StaticMethod()}, opts...)...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DatasourcePlugin_FetchClient = grpc.ServerStreamingClient[FetchEvent]

type DatasourcePluginServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	Validate(context.Context, *ConfigRequest) (*Empty, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error)
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchEvent]) error
	mustEmbedUnimplementedDatasourcePluginServer()
}

type UnimplementedDatasourcePluginServer struct{}

func (UnimplementedDatasourcePluginServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedDatasourcePluginServer) Validate(context.Context, *ConfigRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedDatasourcePluginServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedDatasourcePluginServer) ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveResourceAncestors not implemented")
}
func (UnimplementedDatasourcePluginServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchEvent]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedDatasourcePluginServer) mustEmbedUnimplementedDatasourcePluginServer() {}
func (UnimplementedDatasourcePluginServer) testEmbeddedByValue()                          {}

type UnsafeDatasourcePluginServer interface{ mustEmbedUnimplementedDatasourcePluginServer() }

func RegisterDatasourcePluginServer(s grpc.ServiceRegistrar, srv DatasourcePluginServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatasourcePlugin_ServiceDesc, srv)
}

func _DatasourcePlugin_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	in := new(FetchRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(DatasourcePluginServer).Fetch(in, &grpc.GenericServerStream[FetchRequest, FetchEvent]{ServerStream: stream})
}

type DatasourcePlugin_FetchServer = grpc.ServerStreamingServer[FetchEvent]

var DatasourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DatasourcePlugin",
	HandlerType: (*DatasourcePluginServer)(nil),
	Methods:     nil,
	Streams:     []grpc.StreamDesc{{StreamName: "Fetch", Handler: _DatasourcePlugin_Fetch_Handler, ServerStreams: true}},
	Metadata:    "plugin/proto/datasource.proto",
}

func init() {
	DatasourcePlugin_ServiceDesc.Methods = []grpc.MethodDesc{
		{MethodName: "GetInfo", Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
			in := new(GetInfoRequest)
			if err := dec(in); err != nil {
				return nil, err
			}
			if interceptor == nil {
				return srv.(DatasourcePluginServer).GetInfo(ctx, in)
			}
			return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: DatasourcePlugin_GetInfo_FullMethodName}, func(ctx context.Context, req interface{}) (interface{}, error) {
				return srv.(DatasourcePluginServer).GetInfo(ctx, req.(*GetInfoRequest))
			})
		}},
		{MethodName: "Validate", Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
			in := new(ConfigRequest)
			if err := dec(in); err != nil {
				return nil, err
			}
			if interceptor == nil {
				return srv.(DatasourcePluginServer).Validate(ctx, in)
			}
			return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: DatasourcePlugin_Validate_FullMethodName}, func(ctx context.Context, req interface{}) (interface{}, error) {
				return srv.(DatasourcePluginServer).Validate(ctx, req.(*ConfigRequest))
			})
		}},
		{MethodName: "ListResources", Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
			in := new(ListResourcesRequest)
			if err := dec(in); err != nil {
				return nil, err
			}
			if interceptor == nil {
				return srv.(DatasourcePluginServer).ListResources(ctx, in)
			}
			return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: DatasourcePlugin_ListResources_FullMethodName}, func(ctx context.Context, req interface{}) (interface{}, error) {
				return srv.(DatasourcePluginServer).ListResources(ctx, req.(*ListResourcesRequest))
			})
		}},
		{MethodName: "ResolveResourceAncestors", Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
			in := new(ResolveResourceAncestorsRequest)
			if err := dec(in); err != nil {
				return nil, err
			}
			if interceptor == nil {
				return srv.(DatasourcePluginServer).ResolveResourceAncestors(ctx, in)
			}
			return interceptor(ctx, in, &grpc.UnaryServerInfo{Server: srv, FullMethod: DatasourcePlugin_ResolveResourceAncestors_FullMethodName}, func(ctx context.Context, req interface{}) (interface{}, error) {
				return srv.(DatasourcePluginServer).ResolveResourceAncestors(ctx, req.(*ResolveResourceAncestorsRequest))
			})
		}},
	}
}
